# 应用服务 WEB 访问端口
server:
    port: 9311

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/smartairport?userUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&useSSL=true
        username: root
        password: 535489
        driver-class-name: com.mysql.cj.jdbc.Driver
    jackson:
        default-property-inclusion: non_null
    servlet:
        multipart:
            max-file-size: -1
            max-request-size: -1


